"""Add detection feedback model for AI learning

Revision ID: 9bd243f87f0c
Revises: 9cdad30844bd
Create Date: 2025-11-30 11:47:09.358420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd243f87f0c'
down_revision = '9cdad30844bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detected_label', sa.String(length=100), nullable=False),
    sa.Column('ai_mapped_ingredient', sa.String(length=100), nullable=True),
    sa.Column('correct_ingredient', sa.String(length=100), nullable=False),
    sa.Column('correct_ingredient_id', sa.Integer(), nullable=True),
    sa.Column('correction_count', sa.Integer(), nullable=True),
    sa.Column('learned_confidence', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['correct_ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_feedback_correct_ingredient'), ['correct_ingredient'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_feedback_detected_label'), ['detected_label'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_feedback_detected_label'))
        batch_op.drop_index(batch_op.f('ix_detection_feedback_correct_ingredient'))

    op.drop_table('detection_feedback')
    # ### end Alembic commands ###
